### ISSUE TITLE
 error:    write after end

### ISSUE THREAD

**Issue by hskww** [i5ting/koa-bigpipe#1]
use vue2 renderToStream,the node server work error

**Comment by i5ting** [comment]
can you provide more info?

**Comment by i5ting** [comment]
基本上没啥可以改的了，判断一下headersSent到头，但目前看可能是你的用法有问题，能多发点代码或错误信息么？

**Comment by hfstack** [comment]
$ npm start                                                     [±master ●]

> koavue2@1.0.0 start /Users/hlf/study/koa2vue2ssr
> NODE_ENV=production node server

server started at http://localhost:3000
data pre-fetch: 8ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:426:15)
    at Object.ctx.write (/Users/hlf/study/koa2vue2ssr/node_modules/.1.0.9@koa-bigpipe/index.js:31:9)
    at PassThrough.renderStream.on.chunk (/Users/hlf/study/koa2vue2ssr/server.js:75:13)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at PassThrough.Readable.push (_stream_readable.js:130:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)




<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>vue-ssr-starter-kit</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <link rel="stylesheet" href="/dist/styles.css">
  </head>
  <body>
    OK
